# @package _global_

defaults:
  - /rearrange/rl_hierarchical_oracle_nav_soc_human
  - override /habitat_baselines/rl/policy@habitat_baselines.rl.policy.main_agent: hl_socnav_human #hl_human #hl_fixed
  - override /habitat_baselines/rl/policy/hierarchical_policy/defined_skills@habitat_baselines.rl.policy.main_agent.hierarchical_policy.defined_skills: oracle_skills_humanoid
  - _self_

hydra:
  job:
    name: 'single_fixedpolicy_oracle'

habitat_baselines:
  log_interval: 1
  video_dir: ${hydra:sweep.dir}/${hydra:sweep.subdir}/video
  tensorboard_dir: ""
  eval_ckpt_path_dir: ""
  checkpoint_folder: ""
  log_file: ""
  evaluate: False
  writer_type: 'tb'
  num_environments: 2

habitat:
  task:
    actions:
      oracle_nav_soc_action:
        spawn_max_dist_to_obj: -1.0
    measurements:
      composite_success:
        must_call_stop: False
      force_terminate:
        max_accum_force: -1.0
        max_instant_force: -1.0

  environment:
    max_episode_steps: 700

  simulator:
    kinematic_mode: True
    ac_freq_ratio: 1
    step_physics: False
